"use client";

import type { StyleId } from "@/types";
import { isRealPhotoStyle } from "@/types";
import { STYLE_ORDER_V2, STYLE_PRESETS } from "@/styles/style-presets";

interface Props {
  value: StyleId;
  onChange: (style: StyleId) => void;
}

/**
 * Character Art Style picker (Phase 3.1 spec §1/§30) — the 6 spec'd choices
 * (Real Photo / Cartoon / Kawaii / Chibi / Comic / Hand Drawn). Each card's
 * preview is generated by this component itself from the Style preset's own
 * emoji/swatch/font data — never a copied reference photo (spec's explicit
 * "ห้ามใช้รูป Copyrighted Reference" for style previews). Non-"real" styles
 * show a small "AI" chip since they only actually transform the character
 * when "Use AI Expressions" is also turned on downstream (spec §3 Mode B) —
 * otherwise the sticker still renders, just with the original photo dressed
 * in that style's decoration/outline/font look (a graceful, honest
 * degradation, never a silently-faked transformation).
 */
export default function StylePicker({ value, onChange }: Props) {
  return (
    <div>
      <h3 className="mb-2 text-sm font-semibold text-slate-700">Style</h3>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
        {STYLE_ORDER_V2.map((id) => {
          const preset = STYLE_PRESETS[id];
          const active = value === id;
          const needsAi = !isRealPhotoStyle(id);
          return (
            <button
              key={id}
              type="button"
              onClick={() => onChange(id)}
              style={{ backgroundColor: active ? preset.swatch : undefined }}
              className={`relative flex flex-col items-center gap-1 rounded-xl border-2 px-3 py-3 text-center transition-all ${
                active ? "border-pink-500 shadow-sm" : "border-slate-200 bg-white hover:border-slate-300"
              }`}
            >
              {needsAi && (
                <span className="absolute right-1.5 top-1.5 rounded-full bg-violet-100 px-1.5 py-0.5 text-[9px] font-bold text-violet-600">
                  AI
                </span>
              )}
              <span className="text-2xl" style={{ fontFamily: preset.fontFamily, fontWeight: preset.fontWeight }}>
                {preset.emoji}
              </span>
              <span className="text-xs font-semibold text-slate-700">{preset.labelTh}</span>
            </button>
          );
        })}
      </div>
      <p className="mt-2 text-[11px] text-slate-400">
        Style ที่มีป้าย &quot;AI&quot; ต้องเปิด &quot;Use AI Expressions&quot; ถึงจะแปลงตัวละครเป็นสไตล์นั้นจริง — ถ้าไม่เปิด
        สติ๊กเกอร์จะยังใช้ภาพต้นฉบับ แต่ตกแต่ง/ฟอนต์/เส้นขอบตามสไตล์ที่เลือก
      </p>
    </div>
  );
}
